library("tree")
library("party")
weather <- read.csv("weather.csv")
str(weather)
require(tree)
View(weather)
summary(weather)
play_golf_tree.dec <- tree(RainTomorrow~Cloud3pm+Sunshine,method = "class",data=weather)
plot(play_golf_tree.dec)
text(play_golf_tree.dec ,all=TRUE,pretty = TRUE,splits = TRUE, cex = 1)
summary(play_golf_tree.dec)
# if cloudat3pm < 6.5 then it won't rain, 
# if cloudat3pm > 6.5 then sunshine is checked if > 9.3 it will not rain,
# if sunshine < 0.5 or between 8.75 and 9.3 then it will rain
c.play_golf_tree <- ctree(RainTomorrow~Cloud3pm+Sunshine,data=weather)
plot(c.play_golf_tree)
# difference between tree generated by tree and ctree is decision making based on the cloudat3pm value