amzn_closing_log <- data.frame(log(amzn_ts))
# Applying additive model log to amzn_ts
# Plotting the result generated by applying additive model log to amzn_ts 
plot(amzn_closing_log, ylab = "amzn_closing_log")